### ISSUE TITLE
fatal error ?

### ISSUE THREAD

**Issue by rikmendes** [danito/KnownMastodon#11]
I'm not sure if I have to put this here or on the facebook plugin issue page: 
but on my personal instance, when I share to FB and Mastodon at the same time I get this error : 
If I share only to facebook there is no issue...any hint ?

Fatal error: require_once(): Failed opening required 'Facebook/Facebook.php' (include_path='/var/www/html/external/htmlpurifier-lite/library:.:/usr/local/lib/php:/var/www/html/IdnoPlugins/Mastodon') in /var/www/html/IdnoPlugins/Mastodon/autoload.php on line 18

**Comment by danito** [comment]
ok I see, the autoload of the classes clashes with the fb class. I'll check this when I'm again near a physical keyboard

**Comment by rikmendes** [comment]
I'm keeping having this from time to time, only workaround I found is to NOT POSSE to facebook at the same time I posse to other channels. than I edit the post again and I posse to facebook. it works :)

**Comment by danito** [comment]
As Posse to FB is deprecated, can we close this?

**Comment by rikmendes** [comment]
Indeed !
