### ISSUE TITLE
Show whole user address as link text for "also on"

### ISSUE THREAD

**Issue by skddc** [danito/KnownMastodon#2]
Currently it only shows the username but not the server part. But the username could potentially be the same for multiple accounts. Also, I think it's just nicer and more accurate to show the whole thing.

**Comment by danito** [comment]
good point.

**Comment by danito** [comment]
reopening.

**Comment by danito** [comment]
you were talking about the : also on 'nickname', not the syndication button.
Normally there should be the Mastodon icon in front of the nickname, but it doesn't work.
For now I'll change it to : also on 'nick@mastodon.server'

**Comment by skddc** [comment]
Oh right, actually both of those should contain the server part I think.

**Comment by danito** [comment]
it breaks a bit the design but leave it for now

**Comment by skddc** [comment]
Thanks! Looking great now.
