### ISSUE TITLE
Pictures not posting to mastodon ?

### ISSUE THREAD

**Issue by rikmendes** [danito/KnownMastodon#6]
I tried to POSSE this post to mastodon : https://www.rmendes.net/2017/instances-of-mastodon-by-number-of-toots
but it won't send a copy there, I'm not sure where to look to give you more debug log on this. 
beside that, status, bookmarks are fine :)

**Comment by danito** [comment]
wondering why this has ever worked.... curl can't handle multidimensional arrays. 
Found a workaround and should work now

**Comment by rikmendes** [comment]
working nicely now :)
