### ISSUE TITLE
Link being attached to toot, while "include permalinks" option is turned off

### ISSUE THREAD

**Issue by skddc** [danito/KnownMastodon#7]
I pulled the repo today and just posted a status. It was posted with a colon and link to the Known page attached to it, although the option for including permalinks is turned off, and the length was not above limit or similar:

https://kosmos.social/@raucao/37803

**Comment by danito** [comment]
now links are only added if you share a bookmark (or if length of status > 500).

**Comment by skddc** [comment]
Thanks!
