### ISSUE TITLE
Blog posts are missing links to the post

### ISSUE THREAD

**Issue by skddc** [danito/KnownMastodon#8]
Blog posts currently just show the title, but no backlink. I think this might be due to my setting to not include permalinks with statuses, but for articles this should always be the case.

**Comment by danito** [comment]
Does it work for Bookmarks ?

**Comment by skddc** [comment]
Haven't tried yet. As soon as I have sth to share again, I'll do! ;)

**Comment by skddc** [comment]
Cool, thanks!
